name: Build NODOC APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build APK
        run: |
          docker pull kivy/buildozer:latest
          docker run --rm \
            -v "$PWD":/home/user/hostcwd \
            --entrypoint /bin/bash \
            kivy/buildozer:latest \
            -c "yes | buildozer android debug"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: NODOC-APK
          path: bin/*.apk
